---
title: Feeling Relaxed
author: ''
date: '2021-06-12'
slug: relaxed
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-06-12T19:25:14+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

With only ... 7 weeks to go. I can feel the end nearing. I had a few busy days trying to learn for my last exam, it was a very doable exam. I only need to push through. While I can taste victory, I need to accept that these remaining few weeks will make or break.

I have until Wednesday to turn in my first experiments part. I can and will push through to do it. The importance of sleep can't be understated. the book I read gives four important and underestimated influences on your sleep. Alcohol, blue light, temperature and natural light. Now let's see what I can do with it.


I have a feeling that I'm relaxed. No real stress and I don't know why. Could it be that I know I have my future in hands? Well I'm not sure yet. I don't have a lot to talk about this week. I've skipped the gym more times, than I would like, but that's okay. I drank more alcohol and ate unhealthy, but that's okay. 

Let's have a change of mindset (lazy) and make this a week to remember. No pressure, just go and keep the steps going. If the end thesis is there. I can relax.

[previous post](/2021/06/07/pareto)

[next post](/2021/06/26/choices)
