---
title: Collaboration
author: ''
date: '2021-03-20'
slug: collab
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-20T22:14:47+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

What makes humans so great? Collaboration! We have evolved to work together -- although some might argue we only fight -- and compared to most animals we actually can collaborate pretty well. The central theme of my current week is that collaboration is damn hard. Especially if your "team" consist of you and one other guy. Everyone needs to know their responsibility and what other peoples responsibilities are. I myself sometimes forget where my duties lie and what other people should fix. I want to help, however that needs to be within certain boundaries. I don't know these boundaries well for myself. Now I will work on perfecting these boundaries more. That's basically what I learned this week. 

I got to rebound back into my thesis. Wish me luck!

[previous post](/2021/03/13/restday)

[next post](#)
