---
title: The Mindset
author: ''
date: '2021-02-14'
slug: mindset
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-02-14T15:39:25+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

I had one goal this week and it was to finish persona 5. I'm around 115 hours in and I still expect at least 10 more hours to go. What a long game, however I'd recommend it if you have to patients haha. A pretty quiet week for myself so I'll note down anything noteworthy I can put done. 

I got a new toy and I'm enjoying it a lot. Didn't expect that to be honest. Note to my future me. Reread this sentence.

Maybe one thing I'd like to focus on is the lack of having a full week. I'm not sure, but this week didn't feel really nice. Maybe a bit lonely because I didn't see anyone and I didn't talk with a lot of friends and or family. I reflected a bit on my past. Actually one thing is the 10th of February when my father died. Around 9 years ago. I celebrated by eating a lot of candy, just as the remaining week. 

That's it for this week. Maybe short. Enjoy the last few days of ice and snow!

[previous post](/2021/02/06/whitesnow)

[next post](/2021/02/21/sunshining)
