---
title: Are we there yet? No.
author: ''
date: '2021-05-30'
slug: arewethereyet
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-05-30T21:31:23+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

With only ... 9 weeks remaining to finish my thesis. I'm worried that I might not make it. I NEED A HERO, or just a better plan.

A bit late this time, but I finished the MOOC Futurelearn, nice tips! Didn't think it would give me such a practical guide to improve my current habits. I'm going to include a SMART planning consistently these remaining weeks. Although I do overestimate my stamina, which means the (R)ealistic part in SMART is my kryptonite. I can imagine there being a lot of tips there that would have been nice to know when I was an undergraduate! At the same time, I would have been ignorant of the tips earlier years, being convinced that I got by well enough anyways. Oh so not regrets, in contrast to last week, the SMART planning does wonders.

The end of lockdown might be closer than I think. With a bit of luck I might get vaccinated in June/July. With a temperature of (current) 25 degrees in the Netherlands, it's also harder to skip on my 'social responsibilities'. I need some breathing room obviously to keep going, however I'm not sure what. Food? Enjoying company? More outside? I don't know. 

I realized having long hair is actually hard. You need to take care of it fairly much, which means it's honestly not really my thing. I'm going to take short hair soon.

I'm working really hard to finish my thesis. I need to finish it. Soon.... 

[previous post](/2021/05/22/tenweeks)

[next post](/2021/06/07/pareto)
