---
title: Four weeks till christmas
author: Stephan van der Putten
date: '2020-11-21'
slug: gyoza
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-11-21T22:24:01+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Only 4 weeks remaining till Christmas and boy do I want to celebrate Christmas for once.

It's been a boring week. I don't remember a lot from it. On Monday I attended my lectures all day. On Tuesday I attended my lectures all afternoon. On Wednesday I talked to the teacher about the next assignment in the afternoon. On Thursday I talked to the same teacher about my Master Thesis and did my mentoring session. On Friday I finished the website for a job of a friend and had a tutoring session with some master students to talk about the 4 remaining weeks till Christmas.

Each year I always have had a lot of deadlines before and after Christmas. This year will be different I hope, as I will be done with most of them and only have one remaining exam after January. Please god let me enjoy my Christmas for once without worries. So once again, 4 weeks remaining let's hope they are manageable.

Till next time!


[previous post](/2020/11/14/saturday)

[next post](#)
