---
title: Alright you got me!
author: Stephan van der Putten
date: '2020-10-19'
slug: alright-you-got-me
categories: []
tags: []
subtitle: ''
summary: 'The results of my test are back and my week has been one big SOG'
authors: []
lastmod: '2020-10-19T21:05:28+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Well, this weeks update will be short. Corona didn't get me. After my friend got a negative back I was almost sure to not have corona.

Weirdly enough the test itself wasn't bad at all for me. Maybe I just got lucky with the testers. I also got my result back within the next day. So really quickly.

My sister visited my place. She's really good in distracting me. So I didn't get anything done.

I have a deadline this week, which is really important and I have been not so productive with it. So I hope I'll make it. 

I got a new phone, the oneplus nord. I'm loving it. 

All in all, I hated this last week because when I get really out of my ritme I have a hard time to get back into it and I stress out. Which is why I haven't worked on my deadline till now. I guess I'll have to go back to serious mode starting tomorrow. 

How do I do that normally? Well I drink a lot of coffee, which is my study drugs and do my usual rituals to relax. Most of the time that's meditation, reading in the breaks and doing a powernap. Furthermore I go to the gym. I start early and I have a nice sleep. Also I force myself in a situation where I have to work (like in the library).

Problem is that I want to go natural and try it without most of my usual stimilus. So no coffee study drugs. I hope to see the results, most of the time I bite of my nails when I get really stressed out. I'm trying to keep them. 

Maybe you are wondering why I don't drink coffee anymore? Well I have been drinking coffee everyday for like weeks/months without a stop and now I feel so overdependant and overestimating my need for caffeine that I'm taking a hard break.

Let's see how things go. Btw my nervous breakdown (I'm exaggerating) is why I haven't written on Saturday. This was an extreme case of SOG (studie ontwijkend gedrag), translated to english: Study evading behaviour. Have a nice week!

[previous post](/2020/10/10/sound-of-silence)

[next post](#)
