---
title: Guilty as charged
author: Stephan van der Putten
date: '2020-10-24'
slug: guilty-as-charged
categories: []
tags: []
subtitle: ''
summary: 'We all have to white lie sometimes.'
authors: []
lastmod: '2020-10-24T15:58:38+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Hi readers. We all have these moments where we realize things are not going the correct way. I have not been true to myself and lost my way. In this weeks post I will talk about white lies, the presidential campaign and how my last few days have been. 

First of white lies. As I said in my previous post I have this huge deadline for ASC and as of today I'm still not there yet. So what is still possible during academia when a deadline is looming? Well you ask for extra time. Which I did and this means I have till Wednesday. Easy right? Well now I'm still in the starting phase of the assignment. So lots of work left! I hope this is the last time in my academic career that I have to ask for extension due to my own lack planning and execution. Second, I have been sleeping a lot and terribly much at the same time. So what to do? I watched the presidential debate live at 3am local time. God how interesting and stupid would it be if Trump would be reelected. It does make great for a great show though.

How have my remaining days been? Well I have been thinking about what being poor means and what will happen when the vaccine for Covid will arrive. This book that I have been reading called Enlightenment Now is written by Steven Pinker. The idea of poor is skewed for me, when I think of poor I think of not being able to provide for yourself because you earn less than a certain amount of money. So what do poor people do, well they have to beg or are not able to do a lot of things and are stuck in the poor spiral state for which it is hard to recover from. On a global scale this might be true, however different countries have different social support and different income and cost of living. As such being poor in The Netherlands and being poor in such other non-western country mean completely different things. In reality I think being poor in the Netherlands is like not being able to buy a lot of stuff regularly, not going on a lot of vacations and not having the most high-end stuff but always going cheap. The realization is that even the poorest in The Netherlands are able to go on vacation, have decent technological access and have food but maybe not always the quality you would expect. Dutch standards are different compared to other countries and as a Dutch person I think that I am poor and have been for a long time without realizing that it is not the standard. A lot of people around me are also poor and have things to say like, if you are able to go on vacation you are not poor. Yeah maybe in other countries, but the Dutch poor is of a higher standard than other poor people in the world. I'll find out if my idea of poor is correct. Once again, comparing yourself with the poorest of the poor and seeing a lot of differences doesn't mean you are not poor yourself. Even the poorest people here can buy nice cloths, however they can't buy much more after that. 

Quick question: are students actually poor officially because a lot of them live below the poverty income in The Netherlands?

What another friend of mine said is that even if the vaccine arrives she would probably not take it. She gave multiple reasons:
- Being young
- Being healthy (a.k.a. not fat)
- The rush of the vaccine means the earlier versions are probably higher risk
Mmh I never thought about it that way, that if you take a vaccine that you would be actually gambling on your own health. I mean it would be a social thing to take the vaccine as you are less likely to spread the virus, but if a person is sick they can get tested quickly and get a vaccine to threat the diseas. So why take a risk and use the (early) vaccine? Without us realizing there are a lot of vaccination given to us, as young as a child, which are wrongly given. With that I mean the test to see if you have a disease has a high false-positive rate, higher than you would expect and the effect sometimes is detable. 

Okay anyways, the remaining week has been me in my bed just sleeping a lot. So now I'm trying to get back in my flow of working on deadlines. I lost my mojo. Speak to you guys later. 

  
[previous post](/2020/10/19/alright-you-got-me)

[next post](/2020/10/31/the-paradox-of-living)
