---
title: A week of vacation and work
author: Stephan van der Putten
date: '2020-10-03'
slug: a-week-of-vacation-and-work
categories: []
tags: []
subtitle: ''
summary: 'I took vacation and chilled with a horse'
authors: []
lastmod: '2020-10-03T17:02:00+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Did you know that today is a special day? A day people in Leiden call Leids Ontzet. However due to certain obvious reasons we can't really celebrate. So instead I went drinking with some friends yesterday night, which was great fun. The drinking 'game' we played is called "club van honderd" which means to take a beer shot every minute for 100 minutes. As you might imagine I was smashed at the end. Anyways that was the end of my vacation week.

Because I did so much for my tutoring company I chose to have a self appointed vacation week, where I did not do anything. So let's get started with my week anyways, starting with Tuesday. I had a mentor meet-up, our sweet mentor coach brought us to a stable. We got to pet a therapy horse and that's basically it. There probably was some hidden analogy to mentoring and a therapy horse. If you can think of it, please let me know down below.

The Wednesday was also very nice. I got to finish my Java book, so I should start programming in that language more often. Furthermore I contacted a professor about a research topic. I'll most likely think of something related to distributed systems. Which for me is very exciting. At the end I visited my sisters and we ate some mashed potatoes with vegetables, which we call "stamppot". That was a day well spend!

TNW is a website that talk about tech stuff and where tech companies do a circle jerk of how amazing they are. The organized an online TNW festival, which had some nice speakers. A friend of mine recommended me a few speakers. The first speaker, talked about how easily we are distracted and what we should do to control this aspect. Which has always been a hot topic for me. Please be aware of how easily you are distracted!

I got a new percolator on Friday, because as some of you might know the french press actually increases cholesterol so you should not drink too much of it. It's nice, coffee is a bit smoother than my french press. So I'll keep using it. On the other side I maybe should stop drinking coffee. Because it's something I drink so regularly I actual feel addicted and I should know how I function without.

The Friday afternoon ended with me tutoring my mentees and just asking some question about balance and goals. We did have a bit of a laugh, however I'm wondering how useful I am to them. Oh yeah my phone died, which is horrible. Now I have to use my old Motorola G5, which actually works pretty well. If you read the intro again, you know how my Friday night went. I have a hangover currently.

Oh yeah the last thing I wanted to talk about is my tutoring company. We got a new kid, which brings us to a total of 8. Which is great! We're going to go discuss business on Sunday and play some ping pong. Sounds like fun to me. Have a great weekend anonymous reader.

[previous post](/2020/09/26/beginning-and-end)

[next post](#)
