---
title: When the first weekend hits, it hits hard
author: Stephan van der Putten
date: '2020-09-05'
slug: when-the-first-weekend-hits-it-hits-hard
categories: []
tags: []
subtitle: ''
summary: 'The week was long, the weekend short'
authors: []
lastmod: '2020-09-05T11:03:23+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

The weekend is here. I felt a chill down my spine when the week started. I noticed my inability to do stats maths and my ability to do it and not trust my intuition. I guess that's just how it is. Learn and learn again that I don't know shit. The week although has been great.

After my initial disappointment when starting with ASC, I rebounded and got my enthusiasm back when starting with DPS. The course is nice to do and will be highly rewarding. Online courses are something else and one of those things is the aspect of meeting people to work together with. Luckily I got a group member to work on DPS immediately. We use some discord channel during our study. Saves the hassle of finding a group member and gives me a broader pool of people to work with.

The same day of DPS we met up for the mentoring of students. I expected a bit more collaboration, however we got a nice surprise. A new student coach for the general student well being and to help us mentors. She was so nice to provide feedback on my powerpoint and give us a warm feeling. 

I also became better friends with one of the mentors, we went smoking and he cooked for us. He cooked hot indian food, curry that was super nice. I can handle my hot food! 

The most nerf wreaking moment of the week? Meeting the tutoring group on Friday. Breaking the ice and getting everyone to feel welcome to talk was `interesting`. It was nice and gave me some energy and a new experience on how to work with people. My goal stays to help them become a better student and on the other side they help me to become a better person.

When the weekend hit, I felt sort of as a relieve. I'm gone for the weekend to visit my uncle, at first I was a bit worried as I had a cold. But I think everything is fine. 

I'm watching the The boys this weekend, what are you guys gonna do?

p.s. I think I like flutter a lot.

[previous post](/2020/08/30/starting-the-year/)

[next post](/2020/09/09/funny-you-might-ask)
