---
title: Happy new year!
author: ''
date: '2021-01-11'
slug: happynewyear
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-01-11T16:24:04+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Happy new 2021! We made it. Do we even want to talk about last year? Noooooooo. As god be my witness if this year is going to be the same. I might as well give up. Let's get back to my life.

I have said farewell to my old friend the orange cat. I met the owner and I now that I know that he's just a beggar for attention and food I won't let him into my house. Apparently his name is Jippy. He still visits my home regularly, but now I just ignore him. Never feed a cat!

Today 11th of January I have started with my Thesis. The previous few days were all spent on my last exam of Statistical Learning, let's hope I don't have a retake for that. I'm still not sure what for research proposal I should turn in, but it seems like benchmarking and doing something with testbeds might be nice. I'm off on the right track. Let's see how long I will survive that 9-17 mentality. 

The first bad news of the year is already around the corner. The lockdown is continuing for another three weeks. Which means I'll celebrate my birthday in a closed environment called my home. On the other hand my sister is visiting me again which is great and nice for my sanity. 

Talking about bad news, I was watching the storming of the Capital of America live. That was quite interesting. Just remember America is weird.

I got a long list of stuff I want to do, especially going back to the gym and getting fit is high on the to-do list. How do I feel right now? I don't know, but seeing as I only have to work on my studies and have less distractions, it seems that coping with boredom and enjoying myself is actually hard. 

Not much to add, live is a bit boring but I hope that will change in 2021.

[previous post](/2020/12/29/isurvived)

[next post](#)
