---
title: The pareto principle
author: ''
date: '2021-06-07'
slug: pareto
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-06-07T11:52:18+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

With only ... 8 weeks remaining to finish my thesis. I'm feeling a lot more confident than last week. Although this last few weeks will ofcourse be make or break for me. I have to pull everything out of the closet. Summon the gang. Light the bonfires. Gather the dragonballs. To make this event happen and to get my well earned summer vacation. 

An interesting thought dropped in my head. What if I continued to do Phd here in Leiden? My current supervisor is looking for a student. I did mention to myself that if there was one subject I'd consider doing it. It would be distributed computing. I have to finish my thesis on time and do it well enough. There are a lot of reasons not do it (pay), but on the other hand you get the chance to keep researching in a field that's both growing and interesting. On the other hand, I might literally lose a few years of my life with the amount of pressure and stress associated with a 'regular' Phd track. What is even left for me in Leiden? I wouldn't know.

I'm starting to notice that my PEDs are influencing my sleep. Just an example. Today I only slept 4-5 hours. I should at least get 7-8 hours of sleep each day to perform well. I am only certain that this is not sustainable. I can hardly remember most of the stuff I'm doing anyways. 

Anyways, because of my great progress last weekend I didn't get to writing. I guess having a deadline around the corner pushes myself to do more in less time. Although I am picky for no real reason. Let's see how I feel in 1 week. I have a lot of balls thrown in the air,
sleep enough, relax enough, sport enough, go to the library enough, graduate enough? I have an exam on Friday. I hope that I can ace that exam, to leave only my thesis. Okay my thoughts are on an errand, let's keep the countdown going. The plan is 6 days of work, using SMART planning and 1-2 days of relaxation. Hold on to the program.

[previous post](/2021/05/30/arewethereyet)

[next post](/2021/06/12/relaxed)
