---
title: Trick and Treat
author: ''
date: '2021-05-10'
slug: trickandtreat
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-05-10T20:21:05+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Can motivation be bought? Well I believe I have found a way. Let's talk about that in a minute. My post of today is a bit later, because I had some family in the weekend drop by as such I wanted to do my weekly posting later. Let's talk about me :).

Well I broke my glasses and was dreading the fact of buying new glasses. My old model was not available anymore, my sight has decreased in my left eye and similar models to my old glasses would not be as cheap as my old glasses. After talking it over with multiple friends, I decided to look online for new glasses. A flood of choices makes it harder to choose, but I don't feel like paying for it. At a moment of clarity in the shower (yes that really happens to people) I realised I still had my older glasses. My current glasses had a broken stick on the left, but my old glasses had a broken stick on the right side. One plus one is two and I just the spare parts to fix my glasses, good as new! This felt like a life hack! 200IQ. 

Recently I found an inspirational youtuber, James Scholz, who livestreams everyday to study 12 hours. If only everyone could be like him, I mean only corona could create a situation where being isolated like him would be doable. He got motivated after reading `atomic habits` (to know how to create the habits), `deep work` (why hard deep work is important) and `you can't hurt me` to motivate him to become the best person he can be. As such I wanted to challenge myself too, but I'll start smaller and increase the burden as I improve. Working on my thesis has been hard lately so I want to work on it 5 times a week for at least 4 hours. With only 12 weeks remaining this means dedication. One way to give extrinsic motivation is by having social commitment, if you have every heard of the website `stickk` that what I am using, so I decided if I don't keep to my goals my sisters get a present of me. I have to report every week to them. Let's see how my first week goes.

Oh my god the nice weather is killing me. The sooner I'm done with my thesis the better. How can I enjoy my life if the weather is literally screaming for me to chill outside. Finish stuff now, get back to thesis mode. Last week I dreaded my thesis supervisor meeting, I bit my nails, I have short nights of sleep and why? Because I couldn't get myself motivated to work on a "simple" framework part of my thesis which was almost copy and paste. So I threw in the towel, said it was too hard and my supervisor was okay with that. Lucky me, now I can do whatever I want to start some experimenting and start investigating actual stuff.

On another note, I belief my most important habit it so start taking more walks. Fun fact, did you know the pareto-principe says that 80% of your work is done in 20% of your time spent. I can state that it is true for me.

[previous post](/2021/05/01/doubletrouble)

[next post](/2021/05/16/regret)
