---
title: Lockdown Strikes Back IV
author: ''
date: '2020-12-19'
slug: lockdownstrikes
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-12-19T14:20:08+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Almost time to say goodbye to 2020. Only 2 weeks remaining. So what I've been thinking about in the last few days is mostly what I want to do next year. Also what can I do next year? We have just landed in a new lockdown, making simple things impossible. At the same time I am preparing for some well earned vacation. 

The first purchase I made from my board compensation is a 1TB storage SSD for my computer. Simple things like things make my life easier, I always had a storage shortage. Now I got a new OS and I can install all the tools. Though it takes time to get my new environment up and running. Great purchase.

A monotone lifestyle like mine includes a lot of casual wasting of time by watching TV shows and movies. Sometimes I stumble upon a nice surprise. I watched the first few episodes of the haunting of hill house on netflix. It has been a long while since I watched something worthy to call scary. You should watch it!

Well Christmas is around the corner so I'm gonna spend some quality time with them. Next week let's see if I got something interesting to note.

Have a nice Christmas!  

[previous post](/2020/12/12/entertainment)

[next post](/2020/12/29/isurvived)
