---
title: One month
author: ''
date: '2021-03-06'
slug: onemonth
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-06T20:36:38+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

So after finally having completed my first month of my master thesis -- I think it has potential for greatness. The best scenario is finishing early, giving me a great summer! Let's see how much I change till that time. Let's once again talk about a few short term goals and long term goals.

The world has not changed, we are still in lockdown. It's pretty boring. In less than two weeks we can vote again. So far it seems I might go for a more green party. I'm watching a lot of TV shows. I got a new fitbit. I went to the gym 4 times. I read a few things. I played on the PS4 again, doom eternal. I got bored.

This week I also received an amazing fake news, religious themed magazine. Lot's of fun to read. The most ridiculous magazine I have read in a while. An eye opener. 

I guess on a positive note. I finally went to the gym four times. I'm aiming for six times a week. It's a bit interesting right now. Some local enforcers gave a warning to the gym this week about having not following the current corona rules. The gym owner doesn't really care much, so whenever enforcers show up, you are warned by a loud alarm and are supposed to run and hide in the back room. That's what happened today. Only the owner forgot us and we had to wait way too long. At least now I got a small story out of it. I feel great sporting this much, so I'll definitely try keeping that up.   

Talk to you next week!

[previous post](/2021/02/27/meritocracy)

[next post](#)
