---
title: What I learned
author: ''
date: '2021-07-11'
slug: what-i-learned
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-07-11T14:31:43+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

The dice have been cast. The deadlines to finish my thesis are known. No backing out anymore no going back. I have to finish it. Reasons to work on it constantly right now are numerous, the reward are great and the penalties endured when I can't finish it is even greater.

My tutoring might have a new job. We got an offer to tutor on a school. Basically we had a meet-up with the school dean online. We basically said our stuff and asked away. Simply said, we had to setup a quotation that would be suitable for the school. Takes a lot of time to argue what a suitable price would be and what we would offer. It's a very interesting process. 

Loving my new macbook. That's all. The air can work quiet and without any problems. So far a good investment. Virtualisation has been the only downside so far. I think it's a matter of time before they fix that.

Lost my watch. Not sure where it could be. Maybe the gym? Furthermore I am stuck on networking stuff. Hopefully I can finish it.

See you next week.  

[previous post](/2021/07/05/3-weeks-remaining)

[next post](#)
